<?php

namespace PROJET\PlatformBundle\Repository;

/**
 * TicketCountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketCountRepository extends \Doctrine\ORM\EntityRepository
{
}
